import mouseinfo, pyautogui, time

#mouseinfo.mouseInfo()
pyautogui.moveTo(1797,9,duration=1)
pyautogui.click()
pyautogui.moveTo(771,386,duration=1)
pyautogui.click()
pyautogui.write("YouTube")
pyautogui.press("Enter")
pyautogui.moveTo(268,322,duration=1)
pyautogui.click()
pyautogui.moveTo(803,116,duration=1)
time.sleep(4)
pyautogui.click()
pyautogui.write("PEIXE zago")
pyautogui.press("Enter")
pyautogui.moveTo(709,840,duration=1)
pyautogui.click()
pyautogui.moveTo(1360,871,duration=1)
pyautogui.click()