from classes_ex_01 import AnimaisMarinhos

animal1 = AnimaisMarinhos(False, 'Estrela-do-mar', 'Patrick Estrela', 'fundo do mar', 0.25)
animal1.apresentar()
animal1.viver_na_agua()
animal1.comer()
animal1.dormir()
animal1.nadar()
print("----x-----")
animal2 = AnimaisMarinhos(True, 'Tubarão', 'Bruce', 'oceano profundo', 3.5)
animal2.apresentar()
animal2.viver_na_agua()
animal2.comer()
animal2.dormir()
animal2.nadar()
print("--------x----")
animal3 = AnimaisMarinhos(True, 'Peixe-palhaço', 'Nemo', 'recife de corais', 0.12)
animal3.apresentar()
animal3.viver_na_agua()
animal3.comer()
animal3.dormir()
animal3.nadar()
print("-----x------")
animal4 = AnimaisMarinhos(False, 'Polvo', 'Otávio', 'rochas submarinas', 1.1)
animal4.apresentar()
animal4.viver_na_agua()
animal4.comer()
animal4.dormir()
animal4.nadar()
print("-----x------")
animal5 = AnimaisMarinhos(True, 'Cavalo-marinho', 'Marinho', 'águas rasas', 0.18)
animal5.apresentar()
animal5.viver_na_agua()
animal5.comer()
animal5.dormir()
animal5.nadar()
print("-----x------")
animal6 = AnimaisMarinhos(True, 'Sardinha', 'Sardinha Júnior', 'cardume costeiro', 0.09)
animal6.apresentar()
animal6.viver_na_agua()
animal6.comer()
animal6.dormir()
animal6.nadar()
print("-----x------")
animal7 = AnimaisMarinhos(False, 'Lula', 'Lulinha', 'fundo arenoso', 0.6)
animal7.apresentar()
animal7.viver_na_agua()
animal7.comer()
animal7.dormir()
animal7.nadar()
print("-----x------")
animal8 = AnimaisMarinhos(True, 'Baiacu', 'Baiacu Bolinha', 'recifes tropicais', 0.25)
animal8.apresentar()
animal8.viver_na_agua()
animal8.comer()
animal8.dormir()
animal8.nadar()
print("-----x------")
animal9 = AnimaisMarinhos(False, 'Água-viva', 'Jelly', 'mares quentes', 0.3)
animal9.apresentar()
animal9.viver_na_agua()
animal9.comer()
animal9.dormir()
animal9.nadar()
print("-----x------")
animal10 = AnimaisMarinhos(True, 'Atum', 'Tonhão', 'alto-mar', 1.2)
animal10.apresentar()
animal10.viver_na_agua()
animal10.comer()
animal10.dormir()
animal10.nadar()
print("-----x------")
animal11 = AnimaisMarinhos(True, 'Salmão', 'Salmix', 'rios e mares', 0.8)
animal11.apresentar()
animal11.viver_na_agua()
animal11.comer()
animal11.dormir()
animal11.nadar()
print("-----x------")
animal12 = AnimaisMarinhos(False, 'Golfinho', 'Flipper', 'oceano azul', 2.0)
animal12.apresentar()
animal12.viver_na_agua()
animal12.comer()
animal12.dormir()
animal12.nadar()
print("-----x------")
animal13 = AnimaisMarinhos(True, 'Raia', 'Ray', 'fundo arenoso', 1.5)
animal13.apresentar()
animal13.viver_na_agua()
animal13.comer()
animal13.dormir()
animal13.nadar()
print("-----x------")
animal14 = AnimaisMarinhos(False, 'Orca', 'Blacky', 'águas frias', 5.0)
animal14.apresentar()
animal14.viver_na_agua()
animal14.comer()
animal14.dormir()
animal14.nadar()
print("-----x------")
animal15 = AnimaisMarinhos(True, 'Peixe-leão', 'Léo', 'recifes de coral', 0.3)
animal15.apresentar()
animal15.viver_na_agua()
animal15.comer()
animal15.dormir()
animal15.nadar()
print("-----x------")
animal16 = AnimaisMarinhos(False, 'Foca', 'Bolinha', 'costas geladas', 1.8)
animal16.apresentar()
animal16.viver_na_agua()
animal16.comer()
animal16.dormir()
animal16.nadar()
print("-----x------")
animal17 = AnimaisMarinhos(False, 'Leão-marinho', 'Léo Marinho', 'ilhas rochosas', 2.1)
animal17.apresentar()
animal17.viver_na_agua()
animal17.comer()
animal17.dormir()
animal17.nadar()
print("-----x------")
animal18 = AnimaisMarinhos(True, 'Peixe-espada', 'Espadinha', 'alto-mar', 2.3)
animal18.apresentar()
animal18.viver_na_agua()
animal18.comer()
animal18.dormir()
animal18.nadar()
print("-----x------")
animal19 = AnimaisMarinhos(False, 'Caranguejo', 'Crabby', 'praia e recifes', 0.25)
animal19.apresentar()
animal19.viver_na_agua()
animal19.comer()
animal19.dormir()
animal19.nadar()
print("-----x------")
animal20 = AnimaisMarinhos(False, 'Tartaruga-marinha', 'Tuga', 'praias e mares tropicais', 1.0)
animal20.apresentar()
animal20.viver_na_agua()
animal20.comer()
animal20.dormir()
animal20.nadar()
